# Introduction to Data Frames

In [1]:
import pandas as pd
path_data = '../../../assets/data/'
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

cones = pd.read_csv(path_data + 'cones.csv')
nba = pd.read_csv(path_data + 'nba_salaries.csv')
movies = pd.read_csv(path_data + 'movies_by_year.csv')

We can now apply Python to analyze data. We will work with data stored in DataFrame structures.

DataFrames are a fundamental way of representing data sets. A DataFrame can be viewed in two ways:

- a sequence of named columns that each describe a single attribute of all entries in a data set, or
- a sequence of rows that each contain all information about a single individual in a data set.
We will study DataFrames in great detail in the next several chapters. For now, we will just introduce a few methods without going into technical details.

The DataFrame cones has been imported for us; later we will see how, but here we will just work with it. First, let's take a look at it.

In [2]:
cones

       Flavor        Color  Price
0  strawberry         pink   3.55
1   chocolate  light brown   4.75
2   chocolate   dark brown   5.25
3  strawberry         pink   5.25
4   chocolate   dark brown   5.25
5   bubblegum         pink   4.75

The DataFrame has six rows. Each row corresponds to one ice cream cone. The ice cream cones are the *individuals*.

Each cone has three attributes: flavor, color, and price. Each column contains the data on one of these attributes, and so all the entries of any single column are of the same kind. Each column has a label. We will refer to columns by their labels.

A DataFrame method is just like a function, but it must operate on a DataFrame. So the call looks like

`name_of_DataFrame.method(arguments)`

For example, if you want to see just the first two rows of a table, you can use the DataFrame method `head`.

Many functions in pandas need a little help from you decideing if you want to think about rows (individuals) or columns (attributes). To help out there's often an argument called `axis`
- `axis =0` means that you want to think about applying your function across a row
- `axis = 1` means that you want to think about applying your function down columns

Sometimes this is becuase the same function can be applied in either direction. For now, we will _almost always_ use `axis = 1`.

In [5]:
cones.head(2)

       Flavor        Color  Price
0  strawberry         pink   3.55
1   chocolate  light brown   4.75

You can replace 2 by any number of rows. If you ask for more than six, you will only get six, because `cones` only has six rows.

## Choosing Sets of Columns
The _double bracket_ noation name_of_dataframe[['column_a','column_b']] creates a new DataFrame consisting of only the specified columns. 
If you assign this _new_ DataFrame to a name, you've just copied your selected data into a new DataFrame. The old one hasn't changed.

In [10]:
cones_noPrice =cones[['Flavor', 'Color']]
cones_noPrice

       Flavor        Color
0  strawberry         pink
1   chocolate  light brown
2   chocolate   dark brown
3  strawberry         pink
4   chocolate   dark brown
5   bubblegum         pink

Cones is still unchanged.

In [11]:
cones

       Flavor        Color  Price
0  strawberry         pink   3.55
1   chocolate  light brown   4.75
2   chocolate   dark brown   5.25
3  strawberry         pink   5.25
4   chocolate   dark brown   5.25
5   bubblegum         pink   4.75

You can also *drop* columns you don't want. The table above can be created by dropping the `Color` column.

In [17]:
cones.drop('Color', axis = 1 ) # Notce here, it doesn't make sense to drop the column 'Color' unless `axis = 1`!

       Flavor  Price
0  strawberry   3.55
1   chocolate   4.75
2   chocolate   5.25
3  strawberry   5.25
4   chocolate   5.25
5   bubblegum   4.75

You can name this new table and look at it again by just typing its name.

In [18]:
no_colors = cones.drop('Color',axis=1)

no_colors

       Flavor  Price
0  strawberry   3.55
1   chocolate   4.75
2   chocolate   5.25
3  strawberry   5.25
4   chocolate   5.25
5   bubblegum   4.75

Like `select`, the `drop` method creates a smaller table and leaves the original table unchanged. In order to explore your data, you can create any number of smaller tables by using choosing or dropping columns. It will do no harm to your original data table.

## Sorting Rows

The `sort_values()` method creates a new DataFrame by arranging the rows of the original table in ascending order of the values in the specified column. 

The Arguments: 
- `by = [list of columns]` this tells you what columns you want to sort by
- `asending = True` list in ascending order. Want descending? Make it `False`. If you leave this off, it will be asceding

Here the `cones` table has been sorted in ascending order of the price of the cones.

In [ ]:
cones.sort_values(by = ['Color']) # Notice that when the values are strings it automatically choose alphabetical order!

       Flavor        Color  Price
2   chocolate   dark brown   5.25
4   chocolate   dark brown   5.25
1   chocolate  light brown   4.75
0  strawberry         pink   3.55
3  strawberry         pink   5.25
5   bubblegum         pink   4.75

In [28]:
cones.sort_values(by = ['Price'], ascending= True)

       Flavor        Color  Price
0  strawberry         pink   3.55
1   chocolate  light brown   4.75
5   bubblegum         pink   4.75
2   chocolate   dark brown   5.25
3  strawberry         pink   5.25
4   chocolate   dark brown   5.25

Like _double backets_ and `drop`, the `sort_values` method leaves the original DataFrame unchanged.

## A small wrinkle: DataFrame vs Series

DataFrames are built to be two diemsional; rows and columns.
- The rows are one dimension (row index)
- The columns are the other dimension (column name)

Even if our DataFrame has only a single column it is built with functionality that allows more than one column

A Series is a one Dimensional object: It can only ever have one column, which means is's basically a labeled array.

When working with a pandas DataFrame, you will sometimes want to access multiple columns or even a single column, but keep the 2D structure. 
Other times you may really only want the single column. 

__How do you get those?__

The choice is in the number of brackets!

- `new_data_frame = old_data_frame[[col_a, col_b, $\ldots$ ]]`: the double brackets must be used because you have more than one column
- `new_data_frame = old_data_frame[[col_a]]`: Here we have only one column, but we're keeping all the structure of a 2D object.
- `new_data_series = old_data_frame[col_a]`: Here we really only care about this array of values so single brackets give us a Series.

In [ ]:
cones[['Color']] # Notice that we have rows indexed by integeres starting at 0 and a column named "Color"

         Color
0         pink
1  light brown
2   dark brown
3         pink
4   dark brown
5         pink

In [ ]:
cones['Color'] # Notice here that we have rows indexed by integers starting at 0 but there's no column name. That information has been disgarded. You can see the name and data-type at the bottom.

0           pink
1    light brown
2     dark brown
3           pink
4     dark brown
5           pink
Name: Color, dtype: str

## Selecting rows that satisfy a condition

Suppose we want all rows that have a specific value in a specific column. You do this all the time when shoping or searching online. Every time you go to a web page and have an option to filter results, you are selecting _rows_ (thing your interested in: socks, hotels, etc.) that satisfy a condition or a collection of conditions. For example, maybe we want to find all the ice cream cones that are pink.

We can easily build a _Series_ of Boolean values that tell us which rows have the "Color" entry as "pink". Once we have this series Pandas allows us to _locate_ the rows whose index is `True` skipping the rows where the index is `False`

In [ ]:
cones['Color'] == 'pink' # Series of booleans

0     True
1    False
2    False
3     True
4    False
5     True
Name: Color, dtype: bool

The `.loc[]` method can be used in many ways. This is one: `df.loc[series of booleans]` filters the DataFrame to only those rows that correspond to `True`.

In [42]:
cones.loc[cones['Color'] == 'pink']

       Flavor Color  Price
0  strawberry  pink   3.55
3  strawberry  pink   5.25
5   bubblegum  pink   4.75

Want to do more than one condition? We just need a little __Boolean__ Logic.

Two things at the same time: `(Condition 1) & (Condition 2)` (it's gotta be the amphersand!)
One thing or the other: `(Condition 1) or (Condition 2)`

Let's find all the pink ice cream cones whose price is less than five dolloars

In [45]:
cones.loc[((cones['Color'] == 'pink') & (cones['Price'] < 5.00))]

       Flavor Color  Price
0  strawberry  pink   3.55
5   bubblegum  pink   4.75

Like all the other table methods in this section, `where` leaves the original table unchanged.

## Example: Salaries in the NBA

"The NBA is the highest paying professional sports league in the world," [reported CNN](http://edition.cnn.com/2015/12/04/sport/gallery/highest-paid-nba-players/) in March 2016. The table `nba` contains the [salaries of all National Basketball Association players](https://www.statcrunch.com/app/index.php?dataid=1843341) in 2015-2016.

Each row represents one player. The columns are:

| **Column Label**   | Description                                         |
|--------------------|-----------------------------------------------------|
| `PLAYER`           | Player's name                                       |
| `POSITION`         | Player's position on team                           |
| `TEAM`             | Team name                                           |
|`SALARY`    | Player's salary in 2015-2016, in millions of dollars|
 
The code for the positions is PG (Point Guard), SG (Shooting Guard), PF (Power Forward), SF (Small Forward), and C (Center). But what follows doesn't involve details about how basketball is played.

The first row shows that Paul Millsap, Power Forward for the Atlanta Hawks, had a salary of almost $\$18.7$ million in 2015-2016.

In [46]:
nba

              PLAYER POSITION                TEAM  '15-'16 SALARY
0       Paul Millsap       PF       Atlanta Hawks       18.671659
1         Al Horford        C       Atlanta Hawks       12.000000
2     Tiago Splitter        C       Atlanta Hawks        9.756250
3        Jeff Teague       PG       Atlanta Hawks        8.000000
4        Kyle Korver       SG       Atlanta Hawks        5.746479
..               ...      ...                 ...             ...
412        Gary Neal       PG  Washington Wizards        2.139000
413     DeJuan Blair        C  Washington Wizards        2.000000
414  Kelly Oubre Jr.       SF  Washington Wizards        1.920240
415   Garrett Temple       SG  Washington Wizards        1.100602
416     Jarell Eddie       SG  Washington Wizards        0.561716

[417 rows x 4 columns]

Fans of Stephen Curry can find his row by using `.loc[]`.

In [47]:
nba.loc[nba['PLAYER'] == 'Stephen Curry']

            PLAYER POSITION                   TEAM  '15-'16 SALARY
121  Stephen Curry       PG  Golden State Warriors       11.370786

We can also create a new table called `warriors` consisting of just the data for the Golden State Warriors.

In [48]:
warriors = nba.loc[nba['TEAM'] == 'Golden State Warriors']
warriors

                PLAYER POSITION                   TEAM  '15-'16 SALARY
117      Klay Thompson       SG  Golden State Warriors       15.501000
118     Draymond Green       PF  Golden State Warriors       14.260870
119       Andrew Bogut        C  Golden State Warriors       13.800000
120     Andre Iguodala       SF  Golden State Warriors       11.710456
121      Stephen Curry       PG  Golden State Warriors       11.370786
122     Jason Thompson       PF  Golden State Warriors        7.008475
123   Shaun Livingston       PG  Golden State Warriors        5.543725
124    Harrison Barnes       SF  Golden State Warriors        3.873398
125  Marreese Speights        C  Golden State Warriors        3.815000
126    Leandro Barbosa       SG  Golden State Warriors        2.500000
127       Festus Ezeli        C  Golden State Warriors        2.008748
128       Brandon Rush       SF  Golden State Warriors        1.270964
129       Kevon Looney       SF  Golden State Warriors        1.131960
130   Anderson Varejao       PF  Golden State Warriors        0.289755

The `nba` table is sorted in alphabetical order of the team names. To see how the players were paid in 2015-2016, it is useful to sort the data by salary. Remember that by default, the sorting is in increasing order.

Another small wrinkle: Every wonder why we can use single, double, or even triple quotes for strings? It's to make sure that we can put quotes inside our quotes! 
Here's another attribute of a DataFrame, `df.columns` will show you the exactc column namtes. Since our column name has single quote in it, you must use double quotes when entering it as a string.

In [53]:
nba.columns

Index(['PLAYER', 'POSITION', 'TEAM', ''15-'16 SALARY'], dtype='str')

In [60]:
nba.sort_values(by=["'15-'16 SALARY"])

                     PLAYER POSITION                 TEAM  '15-'16 SALARY
267  Thanasis Antetokounmpo       SF      New York Knicks        0.030888
326            Jordan McRae       SG         Phoenix Suns        0.049709
327          Cory Jefferson       PF         Phoenix Suns        0.049709
324         Orlando Johnson       SG         Phoenix Suns        0.055722
325            Phil Pressey       PG         Phoenix Suns        0.055722
..                      ...      ...                  ...             ...
131           Dwight Howard        C      Houston Rockets       22.359364
255         Carmelo Anthony       SF      New York Knicks       22.875000
72             LeBron James       SF  Cleveland Cavaliers       22.970500
29              Joe Johnson       SF        Brooklyn Nets       24.894863
169             Kobe Bryant       SF   Los Angeles Lakers       25.000000

[417 rows x 4 columns]

These figures are somewhat difficult to compare as some of these players changed teams during the season and received salaries from more than one team; only the salary from the last team appears in the table.  

The CNN report is about the other end of the salary scale – the players who were among the highest paid in the world. To identify these players we can sort in descending order of salary and look at the top few rows.

In [61]:
nba.sort_values(by=["'15-'16 SALARY"], ascending= False)

                     PLAYER POSITION                 TEAM  '15-'16 SALARY
169             Kobe Bryant       SF   Los Angeles Lakers       25.000000
29              Joe Johnson       SF        Brooklyn Nets       24.894863
72             LeBron James       SF  Cleveland Cavaliers       22.970500
255         Carmelo Anthony       SF      New York Knicks       22.875000
131           Dwight Howard        C      Houston Rockets       22.359364
..                      ...      ...                  ...             ...
325            Phil Pressey       PG         Phoenix Suns        0.055722
324         Orlando Johnson       SG         Phoenix Suns        0.055722
326            Jordan McRae       SG         Phoenix Suns        0.049709
327          Cory Jefferson       PF         Phoenix Suns        0.049709
267  Thanasis Antetokounmpo       SF      New York Knicks        0.030888

[417 rows x 4 columns]

The late Kobe Bryant was the highest earning NBA player in 2015-2016.