# Pandas DataFrames

DataFrames are a fundamental object type for representing data sets.
A table can be viewed in two ways:
- a sequence of named columns
- a sequence of rows

In [1]:
import numpy as np
import pandas as pd
np.set_printoptions(threshold=50)
path_data = '../../assets/data/'

## Creating Empty Tables

In [2]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

## Adding Columns

Notice that we added a column by putting a _dictionary_ as the argument for `pd.DataFrame`. That's the most direct way to create a DataFrame, with a dictionary. The keys will be the column names and the values should be np.array's that give the column.

In [3]:
pd.DataFrame({'Number of petals': np.array([8,34,5])})

   Number of petals
0                 8
1                34
2                 5

In [4]:
pd.DataFrame({'Number of petals': np.array([8,34,5]), 'Name': np.array(['lotus','sunflower','rose'])})

   Number of petals       Name
0                 8      lotus
1                34  sunflower
2                 5       rose

Below we see another way of adding a column with the method `.assign()`. The stirng the column name is 'Color' and its values are the corresponding array. Why would you do this? Again, it has some special behaviors that are different: `.assign()` always returns an new DataFrame and won't overeight the current one unless you re-assign it.

In [ ]:
flowers = pd.DataFrame({'Number of petals': np.array([8,34,5]), 'Name': np.array(['lotus','sunflower','rose'])})
new_flowers = flowers.assign(Color=np.array(['pink','yellow','red']))

In [ ]:
new_flowers

   Number of petals       Name   Color
0                 8      lotus    pink
1                34  sunflower  yellow
2                 5       rose     red

In [ ]:
# We can update the values of the 'Name' column, without changing the original DataFrame.
new_flowers.assign(Name=np.array(['Tom', 'Dick', 'Harry']))

   Number of petals   Name   Color
0                 8    Tom    pink
1                34   Dick  yellow
2                 5  Harry     red

In [15]:
new_flowers

   Number of petals       Name   Color
0                 8      lotus    pink
1                34  sunflower  yellow
2                 5       rose     red

In [ ]:
# If we update the column this way, the original DataFrame is changed
new_flowers['Name'] = np.array(['Tom', 'Dick', 'Harry'])

In [17]:
new_flowers

   Number of petals   Name   Color
0                 8    Tom    pink
1                34   Dick  yellow
2                 5  Harry     red

## Reading CSV

This is something we will do lots of: reading data from a .csv file (comma seperated values). There are lots of arguments to learn, but we'll learn them as we go. For now what you need is the _file path_ to your data.

In [18]:
minard = pd.read_csv(path_data + 'minard.csv')
minard

   Longitude  Latitude         City Direction  Survivors
0       32.0      54.8     Smolensk   Advance     145000
1       33.2      54.9  Dorogobouge   Advance     140000
2       34.4      55.5        Chjat   Advance     127100
3       37.6      55.8       Moscou   Advance     100000
4       34.3      55.2        Wixma   Retreat      55000
5       32.0      54.6     Smolensk   Retreat      24000
6       30.4      54.4       Orscha   Retreat      20000
7       26.8      54.3    Moiodexno   Retreat      12000

## Shape of a DataFrame: number of rows and number of columns

- the first entry (index 0) is the number of rows
- the second entry (index 1) is the number of columns

In [19]:
minard.shape

(8, 5)

In [20]:
minard.shape[0]

8

In [24]:
minard.shape[1]

5

## Column Labels

Very often we will need to access, and perhaps edit, the names of the columns in a pandas DataFrame.

In [28]:
# get a list (well, technicall it's not a list but..) of the columns
minard.columns

Index(['Longitude', 'Latitude', 'City', 'Direction', 'Survivors'], dtype='str')

Want to change the name of a column? Use the `.rename()` method. Its argument is a dictionary formatted as `old_name : new_name`. You can change the name and assign it to a new data frame or re-assign the old DataFrame

In [31]:
new_minard = minard.rename(columns={'City':'City Name'})
new_minard

   Longitude  Latitude    City Name Direction  Survivors
0       32.0      54.8     Smolensk   Advance     145000
1       33.2      54.9  Dorogobouge   Advance     140000
2       34.4      55.5        Chjat   Advance     127100
3       37.6      55.8       Moscou   Advance     100000
4       34.3      55.2        Wixma   Retreat      55000
5       32.0      54.6     Smolensk   Retreat      24000
6       30.4      54.4       Orscha   Retreat      20000
7       26.8      54.3    Moiodexno   Retreat      12000

In [32]:
minard

   Longitude  Latitude         City Direction  Survivors
0       32.0      54.8     Smolensk   Advance     145000
1       33.2      54.9  Dorogobouge   Advance     140000
2       34.4      55.5        Chjat   Advance     127100
3       37.6      55.8       Moscou   Advance     100000
4       34.3      55.2        Wixma   Retreat      55000
5       32.0      54.6     Smolensk   Retreat      24000
6       30.4      54.4       Orscha   Retreat      20000
7       26.8      54.3    Moiodexno   Retreat      12000

In [30]:
minard

   Longitude  Latitude         City Direction  Survivors
0       32.0      54.8     Smolensk   Advance     145000
1       33.2      54.9  Dorogobouge   Advance     140000
2       34.4      55.5        Chjat   Advance     127100
3       37.6      55.8       Moscou   Advance     100000
4       34.3      55.2        Wixma   Retreat      55000
5       32.0      54.6     Smolensk   Retreat      24000
6       30.4      54.4       Orscha   Retreat      20000
7       26.8      54.3    Moiodexno   Retreat      12000

In [33]:
# reassign 
minard = minard.rename(columns={'City':'City Name'})
minard

   Longitude  Latitude    City Name Direction  Survivors
0       32.0      54.8     Smolensk   Advance     145000
1       33.2      54.9  Dorogobouge   Advance     140000
2       34.4      55.5        Chjat   Advance     127100
3       37.6      55.8       Moscou   Advance     100000
4       34.3      55.2        Wixma   Retreat      55000
5       32.0      54.6     Smolensk   Retreat      24000
6       30.4      54.4       Orscha   Retreat      20000
7       26.8      54.3    Moiodexno   Retreat      12000

## Access Columns

We've seen some of this before -this is just a little more in-depth. Recall: one bracket gives a series and two brackets gives a DataFrame

In [35]:
minard[['Survivors']]

   Survivors
0     145000
1     140000
2     127100
3     100000
4      55000
5      24000
6      20000
7      12000

### .iloc[]
The .iloc[] accessor in pandas is used for position-based indexing, meaning it selects data based on integer positions rather than labels. You can think of it like Python list slicing applied to rows and columns of a table: the first position is 0, the second is 1, and so on. Inside the brackets, you specify row positions first and column positions second, separated by a comma (for example, df.iloc[0:3, 1]). Slices follow the usual “start:stop” rule, where the start is included and the stop is excluded. This makes .iloc[] especially useful when you want to work with data by its order, regardless of how the rows or columns are labeled.

In [50]:
# all rows, column 4 (fifth column)
minard.iloc[:,4]

0    145000
1    140000
2    127100
3    100000
4     55000
5     24000
6     20000
7     12000
Name: Survivors, dtype: int64

In [52]:
# entry in row 0 and column 0
minard.iloc[0,4]

np.int64(145000)

In [53]:
# Entry in row 5 and column 4
minard.iloc[5,4]

np.int64(24000)

## Working with Columns

Here's a sligthly more advanced example. A few things to keep in mind.
- Depending on what you know, you may want to combine different methods of accessing data.
- `.iloc[]` returns a pandas DataFrame if you ask for more than 1 column
- `.iloc[]` returns a series if you ask for exacly one column
- `.iloc[]` can be forced to return a DataFrame of one column. 

Check out the following examples to see the details

In [ ]:
 # we asked for two columns, so we must get a DataFrame. Notice the slicing!! start at 0, go upto 4 (but not including) by 2
minard.iloc[:, 0:4:2]

   Longitude    City Name
0       32.0     Smolensk
1       33.2  Dorogobouge
2       34.4        Chjat
3       37.6       Moscou
4       34.3        Wixma
5       32.0     Smolensk
6       30.4       Orscha
7       26.8    Moiodexno

In [ ]:
# we asked for one column so it gave us a Series
minard.iloc[:, 0]

0    32.0
1    33.2
2    34.4
3    37.6
4    34.3
5    32.0
6    30.4
7    26.8
Name: Longitude, dtype: float64

In [ ]:
# We put a second bracket (double bracket!!) around the column index, and instead of a Series we got a DataFrame!
minard.iloc[:, [0]]

   Longitude
0       32.0
1       33.2
2       34.4
3       37.6
4       34.3
5       32.0
6       30.4
7       26.8

In [65]:
#We get thge first row as a series (this is a little weird)
minard.iloc[0, :]

Longitude                32.0
Latitude                 54.8
City Name            Smolensk
Direction             Advance
Survivors              145000
Percent_Surviving         1.0
Name: 0, dtype: object

In [ ]:
# Here we get it as a DataFrame (double-ish brackets again!)
minard.iloc[[0], :]

   Longitude  Latitude City Name Direction  Survivors  Percent_Surviving
0       32.0      54.8  Smolensk   Advance     145000                1.0

One nice thing about pandas data structures is that they are prepared for you to do arithmeitc on them -they are kind like numpy arrays in that way. 
Look through the next section of code to make sure you see what's going on.

In [66]:
initial = minard['Survivors'].iloc[0] # this is picking out a number
minard = minard.assign(Percent_Surviving=minard['Survivors']/initial) #this divides all the Survivors column by initial to get a percentage. It's then reassigned!
minard

   Longitude  Latitude    City Name Direction  Survivors  Percent_Surviving
0       32.0      54.8     Smolensk   Advance     145000           1.000000
1       33.2      54.9  Dorogobouge   Advance     140000           0.965517
2       34.4      55.5        Chjat   Advance     127100           0.876552
3       37.6      55.8       Moscou   Advance     100000           0.689655
4       34.3      55.2        Wixma   Retreat      55000           0.379310
5       32.0      54.6     Smolensk   Retreat      24000           0.165517
6       30.4      54.4       Orscha   Retreat      20000           0.137931
7       26.8      54.3    Moiodexno   Retreat      12000           0.082759

In [67]:
minard.style.format({'Percent_Surviving':'{:.2%}'}) # Here we are updatind the format by rounding to 2 decimals and adding a percent sign (don't worry about the det.s)

## Selecting Columns

Now we're going to explor a few more ways of selecting columns. Some of these you've seen before.

In [ ]:
minard[['Longitude','Latitude']] #by name with doube brackets.

   Longitude  Latitude
0       32.0      54.8
1       33.2      54.9
2       34.4      55.5
3       37.6      55.8
4       34.3      55.2
5       32.0      54.6
6       30.4      54.4
7       26.8      54.3

In [ ]:
minard.iloc[:,[0,1]] # with integer location using our slicing style.

   Longitude  Latitude
0       32.0      54.8
1       33.2      54.9
2       34.4      55.5
3       37.6      55.8
4       34.3      55.2
5       32.0      54.6
6       30.4      54.4
7       26.8      54.3

In [ ]:
minard[['Survivors']] # a single column as a dataframe

   Survivors
0     145000
1     140000
2     127100
3     100000
4      55000
5      24000
6      20000
7      12000

In [ ]:
minard['Survivors'] # a single column as a series

0    145000
1    140000
2    127100
3    100000
4     55000
5     24000
6     20000
7     12000
Name: Survivors, dtype: int64

In [ ]:
minard.drop(columns=['Longitude','Latitude','Direction']) # Droping columns by name. Returns a new DataFrame. Leaves the old one unchanged.

     City Name  Survivors  Percent_Surviving
0     Smolensk     145000           1.000000
1  Dorogobouge     140000           0.965517
2        Chjat     127100           0.876552
3       Moscou     100000           0.689655
4        Wixma      55000           0.379310
5     Smolensk      24000           0.165517
6       Orscha      20000           0.137931
7    Moiodexno      12000           0.082759

In [49]:
minard

   Longitude  Latitude    City Name Direction  Survivors  Percent_Surviving
0       32.0      54.8     Smolensk   Advance     145000           1.000000
1       33.2      54.9  Dorogobouge   Advance     140000           0.965517
2       34.4      55.5        Chjat   Advance     127100           0.876552
3       37.6      55.8       Moscou   Advance     100000           0.689655
4       34.3      55.2        Wixma   Retreat      55000           0.379310
5       32.0      54.6     Smolensk   Retreat      24000           0.165517
6       30.4      54.4       Orscha   Retreat      20000           0.137931
7       26.8      54.3    Moiodexno   Retreat      12000           0.082759