# Selecting Rows with pandas

In this notebook, we learn how to select specific rows from a pandas DataFrame based on position or conditions.

In [1]:
import pandas as pd
import numpy as np
path_data = '../../../assets/data/'

## Load the Data

In [2]:
nba = pd.read_csv(path_data + 'nba_salaries.csv')
nba = nba.rename(columns={"'15-'16 SALARY": 'SALARY'})
nba.head()

           PLAYER POSITION           TEAM     SALARY
0    Paul Millsap       PF  Atlanta Hawks  18.671659
1      Al Horford        C  Atlanta Hawks  12.000000
2  Tiago Splitter        C  Atlanta Hawks   9.756250
3     Jeff Teague       PG  Atlanta Hawks   8.000000
4     Kyle Korver       SG  Atlanta Hawks   5.746479

## Selecting Specific Rows by Position
We can select rows using `.iloc[]`, which uses integer positions.

In [6]:
nba.iloc[[0]]

         PLAYER POSITION           TEAM     SALARY
0  Paul Millsap       PF  Atlanta Hawks  18.671659

In [4]:
nba.iloc[3:6]

            PLAYER POSITION           TEAM    SALARY
3      Jeff Teague       PG  Atlanta Hawks  8.000000
4      Kyle Korver       SG  Atlanta Hawks  5.746479
5  Thabo Sefolosha       SF  Atlanta Hawks  4.000000

To get the top 5 highest paid players, we sort first and then take the first 5 rows.

In [5]:
nba.sort_values('SALARY', ascending=False).iloc[0:5]

              PLAYER POSITION                 TEAM     SALARY
169      Kobe Bryant       SF   Los Angeles Lakers  25.000000
29       Joe Johnson       SF        Brooklyn Nets  24.894863
72      LeBron James       SF  Cleveland Cavaliers  22.970500
255  Carmelo Anthony       SF      New York Knicks  22.875000
131    Dwight Howard        C      Houston Rockets  22.359364

## Selecting Rows by Condition
We can filter rows using boolean conditions.

In [7]:
nba[nba['SALARY'] > 10]

             PLAYER POSITION                TEAM     SALARY
0      Paul Millsap       PF       Atlanta Hawks  18.671659
1        Al Horford        C       Atlanta Hawks  12.000000
29      Joe Johnson       SF       Brooklyn Nets  24.894863
30   Thaddeus Young       PF       Brooklyn Nets  11.235955
42     Al Jefferson        C   Charlotte Hornets  13.500000
..              ...      ...                 ...        ...
368   DeMar DeRozan       SG     Toronto Raptors  10.050000
383  Gordon Hayward       SF           Utah Jazz  15.409570
400       John Wall       PG  Washington Wizards  15.851950
401    Nene Hilario        C  Washington Wizards  13.000000
402   Marcin Gortat        C  Washington Wizards  11.217391

[69 rows x 4 columns]

Sort those players by salary:

In [8]:
nba[nba['SALARY'] > 10].sort_values('SALARY')

              PLAYER POSITION                 TEAM     SALARY
368    DeMar DeRozan       SG      Toronto Raptors  10.050000
298   Gerald Wallace       SF   Philadelphia 76ers  10.105855
204        Luol Deng       SF           Miami Heat  10.151612
144      Monta Ellis       SG       Indiana Pacers  10.300000
95   Wilson Chandler       SF       Denver Nuggets  10.449438
..               ...      ...                  ...        ...
131    Dwight Howard        C      Houston Rockets  22.359364
255  Carmelo Anthony       SF      New York Knicks  22.875000
72      LeBron James       SF  Cleveland Cavaliers  22.970500
29       Joe Johnson       SF        Brooklyn Nets  24.894863
169      Kobe Bryant       SF   Los Angeles Lakers  25.000000

[69 rows x 4 columns]

Find Stephen Curry's row:

In [11]:
nba.loc[nba['PLAYER'] == 'Stephen Curry']

            PLAYER POSITION                   TEAM     SALARY
121  Stephen Curry       PG  Golden State Warriors  11.370786

Select all players from a specific team:

In [12]:
nba.loc[nba['TEAM'] == 'Golden State Warriors']

                PLAYER POSITION                   TEAM     SALARY
117      Klay Thompson       SG  Golden State Warriors  15.501000
118     Draymond Green       PF  Golden State Warriors  14.260870
119       Andrew Bogut        C  Golden State Warriors  13.800000
120     Andre Iguodala       SF  Golden State Warriors  11.710456
121      Stephen Curry       PG  Golden State Warriors  11.370786
122     Jason Thompson       PF  Golden State Warriors   7.008475
123   Shaun Livingston       PG  Golden State Warriors   5.543725
124    Harrison Barnes       SF  Golden State Warriors   3.873398
125  Marreese Speights        C  Golden State Warriors   3.815000
126    Leandro Barbosa       SG  Golden State Warriors   2.500000
127       Festus Ezeli        C  Golden State Warriors   2.008748
128       Brandon Rush       SF  Golden State Warriors   1.270964
129       Kevon Looney       SF  Golden State Warriors   1.131960
130   Anderson Varejao       PF  Golden State Warriors   0.289755

## Multiple Conditions
We can combine conditions using `&` (and) and `|` (or).

In [13]:
nba.loc[(nba['POSITION'] == 'PG') & (nba['SALARY'] > 15)]

                PLAYER POSITION                   TEAM     SALARY
60        Derrick Rose       PG          Chicago Bulls  20.093064
74        Kyrie Irving       PG    Cleveland Cavaliers  16.407501
156         Chris Paul       PG   Los Angeles Clippers  21.468695
269  Russell Westbrook       PG  Oklahoma City Thunder  16.744218
400          John Wall       PG     Washington Wizards  15.851950

## Range Conditions
We can select rows within a range.

In [14]:
nba.loc[(nba['SALARY'] >= 10) & (nba['SALARY'] < 10.3)]

             PLAYER POSITION                TEAM     SALARY
204       Luol Deng       SF          Miami Heat  10.151612
298  Gerald Wallace       SF  Philadelphia 76ers  10.105855
356     Danny Green       SG   San Antonio Spurs  10.000000
368   DeMar DeRozan       SG     Toronto Raptors  10.050000

If no rows match, we get an empty DataFrame.

In [15]:
nba.loc[nba['PLAYER'] == 'Barack Obama']

Empty DataFrame
Columns: [PLAYER, POSITION, TEAM, SALARY]
Index: []

## String Filtering
We can filter based on whether text contains a substring.

In [16]:
nba.loc[nba['TEAM'].str.contains('Warriors')]

                PLAYER POSITION                   TEAM     SALARY
117      Klay Thompson       SG  Golden State Warriors  15.501000
118     Draymond Green       PF  Golden State Warriors  14.260870
119       Andrew Bogut        C  Golden State Warriors  13.800000
120     Andre Iguodala       SF  Golden State Warriors  11.710456
121      Stephen Curry       PG  Golden State Warriors  11.370786
122     Jason Thompson       PF  Golden State Warriors   7.008475
123   Shaun Livingston       PG  Golden State Warriors   5.543725
124    Harrison Barnes       SF  Golden State Warriors   3.873398
125  Marreese Speights        C  Golden State Warriors   3.815000
126    Leandro Barbosa       SG  Golden State Warriors   2.500000
127       Festus Ezeli        C  Golden State Warriors   2.008748
128       Brandon Rush       SF  Golden State Warriors   1.270964
129       Kevon Looney       SF  Golden State Warriors   1.131960
130   Anderson Varejao       PF  Golden State Warriors   0.289755

In [17]:
nba.loc[nba['POSITION'].str.contains('G')]

               PLAYER POSITION                TEAM    SALARY
3         Jeff Teague       PG       Atlanta Hawks  8.000000
4         Kyle Korver       SG       Atlanta Hawks  5.746479
8     Dennis Schroder       PG       Atlanta Hawks  1.763400
9    Tim Hardaway Jr.       SG       Atlanta Hawks  1.304520
11   Jason Richardson       SG       Atlanta Hawks  0.947276
..                ...      ...                 ...       ...
409     Alan Anderson       SG  Washington Wizards  4.000000
411    Ramon Sessions       PG  Washington Wizards  2.170465
412         Gary Neal       PG  Washington Wizards  2.139000
415    Garrett Temple       SG  Washington Wizards  1.100602
416      Jarell Eddie       SG  Washington Wizards  0.561716

[181 rows x 4 columns]

## Negation
Use `~` to negate a condition.

In [18]:
nba.loc[~(nba['TEAM'] == 'Cleveland Cavaliers') & (nba['SALARY'] >= 20)]

              PLAYER POSITION                   TEAM     SALARY
29       Joe Johnson       SF          Brooklyn Nets  24.894863
60      Derrick Rose       PG          Chicago Bulls  20.093064
131    Dwight Howard        C        Houston Rockets  22.359364
156       Chris Paul       PG   Los Angeles Clippers  21.468695
169      Kobe Bryant       SF     Los Angeles Lakers  25.000000
201       Chris Bosh       PF             Miami Heat  22.192730
202      Dwyane Wade       SG             Miami Heat  20.000000
255  Carmelo Anthony       SF        New York Knicks  22.875000
268     Kevin Durant       SF  Oklahoma City Thunder  20.158622

## Summary
- Use `.iloc[]` for position-based selection
- Use `.loc[]` with boolean conditions for filtering
- Combine conditions with `&` and `|`
- Use `.str.contains()` for text matching
- Use `~` for negation