# Example: Population Trends (Pandas Version)

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load data from URL
data = 'http://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2019/nc-est2019-agesex-res.csv'
full_census_df = pd.read_csv(data)
full_census_df.head()

,SEX,AGE,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
0,0,0,3944153,3944160,3951430,3963092,3926570,3931258,3954787,3983981,3954773,3893990,3815343,3783052
1,0,1,3978070,3978090,3957730,3966225,3977549,3942698,3948891,3973133,4002903,3972711,3908830,3829599
2,0,2,4096929,4096939,4090621,3970654,3978925,3991740,3958711,3966321,3991349,4020045,3987032,3922044
3,0,3,4119040,4119051,4111688,4101644,3981531,3991017,4005928,3974351,3982984,4006946,4033038,3998665
4,0,4,4063170,4063186,4077346,4121488,4111490,3992502,4004032,4020292,3989750,3997280,4018719,4043323

In [3]:
# Select relevant columns
partial_df = full_census_df[['SEX','AGE','POPESTIMATE2014','POPESTIMATE2019']]
partial_df.head()

   SEX  AGE  POPESTIMATE2014  POPESTIMATE2019
0    0    0          3954787          3783052
1    0    1          3948891          3829599
2    0    2          3958711          3922044
3    0    3          4005928          3998665
4    0    4          4004032          4043323

In [4]:
# Rename columns
us_pop = partial_df.rename(columns={
    'POPESTIMATE2014':'2014',
    'POPESTIMATE2019':'2019'
})
us_pop.head()

   SEX  AGE     2014     2019
0    0    0  3954787  3783052
1    0    1  3948891  3829599
2    0    2  3958711  3922044
3    0    3  4005928  3998665
4    0    4  4004032  4043323

In [5]:
# Filter SEX == 0 and drop column
us_pop_by_age = us_pop[us_pop['SEX'] == 0].drop(columns=['SEX'])
us_pop_by_age.head()

   AGE     2014     2019
0    0  3954787  3783052
1    1  3948891  3829599
2    2  3958711  3922044
3    3  4005928  3998665
4    4  4004032  4043323

In [6]:
# Ages 97-100
us_pop_by_age[(us_pop_by_age['AGE'] >= 97) & (us_pop_by_age['AGE'] < 101)]

     AGE   2014    2019
97    97  82948  116969
98    98  59546   86150
99    99  41277   57124
100  100  70685  100322

In [8]:
# Compute change
us_pop_by_age['Change'] = us_pop_by_age['2019'] - us_pop_by_age['2014']
us_pop_by_age['Percent Change'] = us_pop_by_age['Change'] / us_pop_by_age['2014']
us_pop_by_age.head()

   AGE     2014     2019  Change  Percent Change
0    0  3954787  3783052 -171735       -0.043425
1    1  3948891  3829599 -119292       -0.030209
2    2  3958711  3922044  -36667       -0.009262
3    3  4005928  3998665   -7263       -0.001813
4    4  4004032  4043323   39291        0.009813

In [9]:
# Total population row (AGE == 999)
us_pop_by_age[us_pop_by_age['AGE'] == 999]

     AGE       2014       2019   Change  Percent Change
101  999  318301008  328239523  9938515        0.031224

In [10]:
# Sort by change
us_pop_by_age[us_pop_by_age['AGE'] < 999].sort_values(by='Change', ascending=False).head()

    AGE     2014     2019  Change  Percent Change
72   72  2191642  3191048  999406        0.456008
68   68  2567511  3345475  777964        0.303003
69   69  2530460  3252423  721963        0.285309
70   70  2461426  3136704  675278        0.274344
71   71  2516392  3083083  566691        0.225200

Take a look at the top few rows. While the percent change is about 3% for the overall population, it jumps to well over 20% for the people in their late sixties and early seventies. This stunning change contributes to what is known as the greying of America.

What could explain this large increase? We can explore this question by examining the years in which the relevant groups were born.

- Those who were in the age group 69 to 72 in 2014 were born in the years 1942 to 1945. The attack on Pearl Harbor was in late 1941, and by 1942 U.S. forces were heavily engaged in a massive war that ended in 1945. 

- Those who were 69 to 72 years old in 2019 were born in the years 1947 to 1950, at the height of the post-WWII baby boom in the United States. 

The post-war jump in births is a major reason for the large changes that we have observed.